// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk93Uh6B8e2DbAijuoVzN_P3VrD9M5Aik',
    appId: '1:390297939113:web:e1bc2d6dc861b809a58db8',
    messagingSenderId: '390297939113',
    projectId: 'manar-612e2',
    authDomain: 'manar-612e2.firebaseapp.com',
    storageBucket: 'manar-612e2.firebasestorage.app',
    measurementId: 'G-QGL0KXPJWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuvoMHJAid_LuDZnGKMWucyJRoBfa4TXA',
    appId: '1:390297939113:android:a6f8ecb7d3bd70f1a58db8',
    messagingSenderId: '390297939113',
    projectId: 'manar-612e2',
    storageBucket: 'manar-612e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbtZvLYA99v4AS_Ykk-TJ67HvcIlRZ4c',
    appId: '1:390297939113:ios:eaebe4bc6bda65cca58db8',
    messagingSenderId: '390297939113',
    projectId: 'manar-612e2',
    storageBucket: 'manar-612e2.firebasestorage.app',
    iosBundleId: 'com.example.manar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbtZvLYA99v4AS_Ykk-TJ67HvcIlRZ4c',
    appId: '1:390297939113:ios:eaebe4bc6bda65cca58db8',
    messagingSenderId: '390297939113',
    projectId: 'manar-612e2',
    storageBucket: 'manar-612e2.firebasestorage.app',
    iosBundleId: 'com.example.manar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk93Uh6B8e2DbAijuoVzN_P3VrD9M5Aik',
    appId: '1:390297939113:web:0f2b4be08e98a4b2a58db8',
    messagingSenderId: '390297939113',
    projectId: 'manar-612e2',
    authDomain: 'manar-612e2.firebaseapp.com',
    storageBucket: 'manar-612e2.firebasestorage.app',
    measurementId: 'G-Z2N3DGJH9Q',
  );
}
