// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:provider/provider.dart';
// import 'package:google_fonts/google_fonts.dart';

// // Import Firebase options (generated by flutterfire configure)
// import 'firebase_options.dart';

// // Import our screens
// import 'screens/welcome_screen.dart';
// import 'screens/auth/login_screen.dart';
// import 'screens/auth/register_screen.dart';
// import 'screens/onboarding/onboarding_flow.dart';
// import 'screens/home/home_screen.dart';
// import 'screens/splash_screen.dart';

// // Import services
// import 'services/auth_services.dart';
// import 'services/user_services.dart';

// // Import constants
// import 'constants/app_theme.dart';

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
  
//   try {
//     // Initialize Firebase with proper options
//     await Firebase.initializeApp(
//       options: DefaultFirebaseOptions.currentPlatform,
//     );
//     print('Firebase initialized successfully');
//   } catch (e) {
//     print('Firebase initialization error: $e');
//   }
  
//   runApp(ManaraApp());
// }

// class ManaraApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return MultiProvider(
//       providers: [
//         ChangeNotifierProvider(create: (_) => AuthService()),
//         ChangeNotifierProvider(create: (_) => UserService()),
//       ],
//       child: MaterialApp(
//         title: 'Manara - Qatar Tourism',
//         theme: AppTheme.lightTheme,
//         debugShowCheckedModeBanner: false,
        
//         // Initial route based on auth state
//         home: AuthStateWrapper(),
        
//         // Define all routes
//         routes: {
//           '/welcome': (context) => WelcomeScreen(),
//           '/login': (context) => LoginScreen(),
//           '/register': (context) => RegisterScreen(),
//           '/onboarding': (context) => OnboardingFlow(),
//           '/home': (context) => HomeScreen(),
//         },
//       ),
//     );
//   }
// }

// class AuthStateWrapper extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return StreamBuilder<User?>(
//       stream: FirebaseAuth.instance.authStateChanges(),
//       builder: (context, snapshot) {
//         // Show splash while checking auth state
//         if (snapshot.connectionState == ConnectionState.waiting) {
//           return SplashScreen();
//         }
        
//         // User is logged in
//         if (snapshot.hasData) {
//           return FutureBuilder<bool>(
//             future: UserService().hasCompletedOnboarding(snapshot.data!.uid),
//             builder: (context, onboardingSnapshot) {
//               if (onboardingSnapshot.connectionState == ConnectionState.waiting) {
//                 return SplashScreen();
//               }
              
//               // Check if user completed onboarding
//               if (onboardingSnapshot.data == true) {
//                 return HomeScreen();
//               } else {
//                 return OnboardingFlow();
//               }
//             },
//           );
//         }
        
//         // User is not logged in
//         return WelcomeScreen();
//       },
//     );
//   }
// }

// main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:provider/provider.dart';
import 'package:google_fonts/google_fonts.dart';

// Import Firebase options (generated by flutterfire configure)
import 'firebase_options.dart';

// Import our screens
import 'screens/welcome_screen.dart';
import 'screens/auth/login_screen.dart';
import 'screens/auth/register_screen.dart';
import 'screens/onboarding/onboarding_flow.dart';
import 'screens/home/home_screen.dart';
import 'screens/splash_screen.dart';

// Import services
import 'services/auth_services.dart';
import 'services/user_services.dart';
import 'services/ai_recommendation_service.dart';

// Import constants
import 'constants/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  try {
    // Initialize Firebase with proper options
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print('Firebase initialized successfully');
  } catch (e) {
    print('Firebase initialization error: $e');
  }
  
  runApp(ManaraApp());
}

class ManaraApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthService()),
        ChangeNotifierProvider(create: (_) => UserService()),
        ChangeNotifierProxyProvider2<UserService, AuthService, AIRecommendationService>(
          create: (context) => AIRecommendationService(
            Provider.of<UserService>(context, listen: false),
            Provider.of<AuthService>(context, listen: false),
          ),
          update: (context, userService, authService, previous) =>
              previous ?? AIRecommendationService(userService, authService),
        ),
      ],
      child: MaterialApp(
        title: 'Manara - Qatar Tourism',
        theme: AppTheme.lightTheme,
        debugShowCheckedModeBanner: false,
        
        // Initial route based on auth state
        // ARWA
        home: AuthStateWrapper(),
        // initialRoute: '/welcome',
        // Define all routes
        routes: {
          // ARWA
          // '/': (context) => AuthStateWrapper(),
          '/welcome': (context) => WelcomeScreen(),
          '/login': (context) => LoginScreen(),
          '/register': (context) => RegisterScreen(),
          '/onboarding': (context) => OnboardingFlow(),
          '/home': (context) => HomeScreen(),
        },
      ),
    );
  }
}

class AuthStateWrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // Show splash while checking auth state
        if (snapshot.connectionState == ConnectionState.waiting) {
          return SplashScreen();
        }
        
        // User is logged in
        if (snapshot.hasData) {
          return FutureBuilder<bool>(
            future: UserService().hasCompletedOnboarding(snapshot.data!.uid),
            builder: (context, onboardingSnapshot) {
              if (onboardingSnapshot.connectionState == ConnectionState.waiting) {
                return SplashScreen();
              }
              
              // Check if user completed onboarding
              if (onboardingSnapshot.data == true) {
                // Initialize AI service when navigating to home
                WidgetsBinding.instance.addPostFrameCallback((_) {
                  final aiService = context.read<AIRecommendationService>();
                  aiService.loadAllRecommendations();
                });
                return HomeScreen();
              } else {
                return OnboardingFlow();
              }
            },
          );
        }
        
        // User is not logged in
        // ARWA 
        WidgetsBinding.instance.addPostFrameCallback((_) {
          Navigator.pushNamedAndRemoveUntil(context, '/welcome', (route) => false);
        });
        return SplashScreen(); 
        // return WelcomeScreen();
      },
    );
  }
}